const employ = [
  {
    id: 1,
    firstName: "Rajesh",
    email: "R@gmail.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Task 1",
        description: "Complete the project report",
        date: "2024-10-15",
        category: "Work",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Task 2",
        description: "Attend the team meeting",
        date: "2024-10-10",
        category: "Meetings",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Task 3",
        description: "Review client feedback",
        date: "2024-10-12",
        category: "Client",
      },
    ],
    taskCount: {
      active: 2,
      newTask: 2,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 2,
    firstName: "Amit",
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Task 1",
        description: "Prepare budget analysis",
        date: "2024-10-20",
        category: "Finance",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Task 2",
        description: "Submit the design mockups",
        date: "2024-10-08",
        category: "Design",
      },
    ],
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 3,
    firstName: "Priya",
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Task 1",
        description: "Organize team lunch",
        date: "2024-09-30",
        category: "Team Building",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Task 2",
        description: "Update website content",
        date: "2024-10-18",
        category: "Web",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Task 3",
        description: "Fix website bugs",
        date: "2024-10-15",
        category: "Development",
      },
    ],
    taskCount: {
      active: 1,
      newTask: 0,
      completed: 1,
      failed: 1,
    },
  },
  {
    id: 4,
    firstName: "Sneha",
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Task 1",
        description: "Plan marketing strategy",
        date: "2024-10-25",
        category: "Marketing",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        title: "Task 2",
        description: "Create social media posts",
        date: "2024-10-22",
        category: "Social Media",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Task 3",
        description: "Conduct market research",
        date: "2024-09-20",
        category: "Research",
      },
    ],
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 5,
    firstName: "Vikram",
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Task 1",
        description: "Prepare presentation for clients",
        date: "2024-10-19",
        category: "Client Work",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        title: "Task 2",
        description: "Arrange the monthly meeting",
        date: "2024-10-02",
        category: "Meetings",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        title: "Task 3",
        description: "Complete the documentation",
        date: "2024-09-29",
        category: "Documentation",
      },
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        title: "Task 4",
        description: "Set up new project proposal",
        date: "2024-10-23",
        category: "Projects",
      },
    ],
    taskCount: {
      active: 2,
      newTask: 2,
      completed: 1,
      failed: 1,
    },
  },
];
const admin = {
  id: 1,
  email: "sayan@example.com",
  password: "123",
};

export const setLocalStorage = () => {
  localStorage.setItem("employ", JSON.stringify(employ));
  localStorage.setItem("admin", JSON.stringify(admin));
};
export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employ"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
